node:
  environment: 'development'

http:
  port: 4000

auth:
  jwt_secret: 'thisisasecret!!!!!4444'
  jwt_expiration: '15min'
  bcrypt_salt_rounds: 8
  refresh_token_expiration_days: 30
  refresh_token_length: 50
  email_confirmation_token_length: 30
  email_confirmation_expiration_hours: 48
  password_reset_token_length: 30
  password_reset_token_expiration_hours: 12

mail:
  smtp_host: 'smtp.mailtrap.io'
  smtp_port: 2525
  smtp_user: 'fa61b87ebd50b0'
  smtp_password: '7f4a2d4fd2c814'
  sender_email_address: 'daniel@reservatio.com'
